### ISSUE TITLE
Buggy

### ISSUE THREAD

**Issue by jonshouse1** [Arsenic-ATG/Text-Editor#45]
Combinations of inserting and moving cursor cause crashes.

```
Program received signal SIGSEGV, Segmentation fault.
>                                                   ^[[D__GI___libc_realloc (oldmem=0x4b5b1b3e0a0d4b5b, bytes=1264261952) at malloc.c:3154
3154    malloc.c: No such file or directory.
(gdb) bt
#0  __GI___libc_realloc (oldmem=0x4b5b1b3e0a0d4b5b, bytes=1264261952) at malloc.c:3154
#1  0x0000555555556b36 in editor_row_insert_char ()
#2  0x0000555555556e1f in editor_insert_char ()
#3  0x0000555555557e43 in editor_process_keypress ()
#4  0x0000555555557f55 in main ()
(gdb) 
>
```

I tried to integrate this code into another project, also got some of these. This may be my doing as I made a number of terminal changes but I suspect it is an error in the core code.
````
free or corruption (!prev)
````

I am going to give up on using this project for now, promising start but very buggy and unclear about its own memory management.

I built it with gcc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0)  Linux Mint with the following options:
```
-O0 -Wall -g -fstack-protector-all
```

This seem to highlight some more bugs.

**Comment by Arsenic-ATG** [comment]
yes, I can confirm that this is a bug in the core code itself. 

thanks for reporting this bug, I am investigating.
